### ISSUE TITLE
Add to Pocket with multiple windows open does not always add the correct tab

### ISSUE THREAD

**Issue by tamarahills** [tamarahills/foxyext#25]
Steps to repro
1. Open a firefox window with a web page in a tab
2. Open a second one with a web page in a tab and have this window active
3.  have foxy running
4. Ask Foxy to "add to pocket"
5.  Foxy shoudl add the article from window 2 to pocket (expected)
Foxy adds the article from window 1 to pocket (actual)

**Comment by ngalkin** [comment]
resolve #28
